export const skills = [
  "ReactJS",
  "JavaScript (Programming Language)",
  "Node.Js",
  "Cascading Style Sheets (CSS)",
  "Amazon Web Services",
  "TypeScript",
  "MongoDB",
  "Python (Programming Language)",
  "MySQL",
  "Java (Programming Language)",
  "HTML",
  "AngularJS",
  "Git",
  "PostgreSQL",
  "Docker",
  "React Redux",
  "Graphql",
  "Restful APIs",
  "Next.js",
  "Vue.js",
  "Django Web Framework",
  "PHP (Programming Language)",
  "Bootstrap (Software)",
  "Github",
  "JIRA",
  "React Native",
  "Express.js",
  "Microsoft Azure",
  "JQuery",
  "Kubernetes",
  "HTML5",
  "Spring-boot",
  "Agile Methodology",
  "C Sharp (Programming Language)",
  "Jenkins",
  "C++ (Programming Language)",
  "Linux",
  "Laravel",
  "Continuous Integration",
  "Tailwind",
  "Cloud Computing",
  "Testing Skills",
  "Application Programming Interfaces (APIs)",
  "Flask (Web Framework)",
  "Scrum Methodology",
  // "Programming Languages",
  "Microsoft SQL Server",
  "Redis",
  "NestJS",
  "Firebase",
  // "Software Version Control",
  "Webpack",
  "Syntactically Awesome Style Sheets (SASS)",
  // "Microservices",
  "Figma",
  "Cypress (Programming Language)",
  "WordPress",
  "Extensible Markup Language (XML)",
  "Apache Kafka",
  "Amazon DynamoDB",
  "Material UI",
  "Oracle Applications",
  "Hibernate (Java)",
  "Junit",
  "Bitbucket",
  "Java Platform Enterprise Edition (J2EE)",
  "Eclipse (Software)",
  ".NET Framework",
  "Selenium",
  "Amazon S3",
  "Amazon Elastic Compute Cloud",
  "Postman",
  "Web Services",
  "Ruby on Rails",
  // "DevOps",
  "NoSQL",
  "Golang",
  "Heroku",
  "Model View Controller (MVC)",
  "JSON",
  "ECMAScript",
  // "Problem Solving",
  "Automation of Tests",
  "Ajax (Programming Language)",
  // "Team Working",
  "Gitlab",
  "Ruby",
  "Apache Tomcat",
  // "Web Technologies",
  // "Software Engineering",
  "Google Cloud",
  "Mocha",
  "Enzymes",
  "Unit Testing",
  "Solidity",
  "RabbitMQ",
  // "Communication Skills",
  "Trello",
  "Vuejs",
  "Java Database Connectivity",
  "Microsoft Visual Studio",
  "SQLite",
  "ASP.NET",
  "Microsoft Windows",
  "Simple Object Access Protocol (SOAP)",
  "Web3.js",
  "Elasticsearch",
  "Project Management",
  "Apache Maven",
  "Design of User Interfaces",
  "Computer Programming",
  "Terraform",
  "Leadership",
  "Object-Oriented Software Development",
  "Web Development",
  "Javaserver Pages",
  "Blockchain",
  "Java Persistence API",
  ".NET Core",
  "Serverless Computing",
  "Shopify",
  "Jasmine",
  "Java Servlet",
  "IntelliJ IDEA",
  "Subversion",
  "Web Applications",
  "Rust (Programming Language)",
  "Apache HTTP Server",
  "Responsive Web Design",
  "Architecture",
  "Circleci",
  "Tensorflow",
  "Mockito",
  "Spring-mvc",
  "Operational Systems",
  "Software Debugging",
  "Kanban",
  "Flutter",
  "Pandas",
  "Pytorch",
  "Shell Script",
  "D3.Js",
  "Automation",
  "Adaptability",
  "Apple IOS",
  "Gulp.js",
  "Unix",
  "PL-SQL",
  "Confluence",
  "NumPy",
  "Machine Learning",
  "Amazon Simple Queue Service (SQS)",
  "Safety Principles",
  "Artificial Intelligence",
  "Spring Security",
  "User Experience",
  "WebSocket",
  "Adobe XD",
  "Scala (Programming Language)",
  "Splunk",
  "Database Administration",
  "Adobe Photoshop",
  "Swift (Programming Language)",
  "Android Studio",
  // "Server Applications",
  // "Systems Development Life Cycle",
  "Apache Spark",
  "Content Management",
  "Software as a Service",
  // "Mentoring",
  // "Algorithms",
  "Nginx",
  "Mobile Application Development",
  "Entity Framework",
  // "Web Api",
  "Microsoft Office",
  "Mern",
  "Oracle WebLogic Server",
  "Infrastructure Management",
  "Snowflake",
  "Ethereum",
  "IBM Websphere Application Server",
  "UML",
  "Windows PowerShell",
  "Grpc",
  "Api Design",
  "Api Gateway",
  "Testing (Software)",
  "Apache Struts",
  "Cucumber (Software)",
  "Gatsby",
  "Unity 3d",
  "NetBeans",
  "Gradle",
  "CodeIgniter",
  "Keras",
  "Three.js",
  "Fastapi",
  "Bash Shell",
  "Data Analysis",
  "Software Design Patterns",
  "Npm(Software)",
  "Grunt (Software)",
  "Oracle Databases",
  "Programming Tools",
  "Symfony",
  "Apache Hadoop",
  "Cloudwatch",
  "Joomla",
  "Time Management",
  "MariaDB",
  "Adobe Illustrator",
  "Identity Management",
  "Adobe",
  "Mobile Application Software",
  "Twilio",
  "Matplotlib",
  "RxJS",
  "AWS Lambda",
  "Swagger",
  "Java Message Service (JMS)",
  "Success Driven Person",
  "Grafana",
  "Cryptography",
  // "Creativity",
  "Spring Framework",
  // "Semantics",
  "Ansible",
  "JavaBeans",
  "Extreme Programming",
  "Microsoft Access",
  "Google Analytics",
  "Drupal",
  "Information Technology",
  "Playwright",
  "Internet Information Services (IIS)",
  "Web Servers",
  "Test-Driven Development (TDD)",
  "Kendo Ui",
  "Web Design",
  "Human-Computer Interaction",
  "Drawing Skills",
  "Code Review",
  "Build Tools",
  "E-Commerce",
  "Full Stack Development",
  "Extensible Stylesheet Language Transformations (XSLT)",
  "Jax Ws",
  "Open Source Technology",
  "Scikit Learn",
  "Friendliness",
  "Spring Data",
  "Spring Cloud",
  "Cassandra",
  "VoIP",
  "Objective-C (Programming Language)",
  "Deep Learning",
  "Kotlin",
  "Testng",
  "Quality Management",
  "Log4j",
  "Pytest",
  "Xamarin",
  "Asana",
  "SQL Stored Procedures",
  "Language Integrated Query",
  "Network Routers",
  "Ubuntu (Operating System)",
  "Systems Design",
  "Java Platform Standard Edition (J2SE)",
  "Networking Skills",
  "Adobe Dreamweaver",
  "Extensible HyperText Markup Language (XHTML)",
  "Data Logging",
  "Visual Basic .NET (Programming Language)",
  "Big Data",
  "Network Server",
  "Moulding Machines",
  "Data Science",
  "Region Management",
  "Containerization",
  "Cloud Engineering",
  "Pyspark",
  "Hubspot",
  "WooCommerce",
  "Graphic Design",
  "Tableau (Software)",
  "Critical Thinking",
  "undefined",
  "OAuth",
  "Web Services Description Language",
  "Lodash",
  "Analytical Thinking",
  "Interpersonal Skills",
  // "Management of Stress",
  "Oracledb",
  "Xunit",
  "MATLAB",
  // "Attention to Detail",
  // "Curiosity",
  "Groovy",
  "Kibana",
  "Prometheus",
  "OpenCV",
  "SQLAlchemy",
  "Sinon",
  "Server-Side",
  "SonarQube",
  "Spring Batch",
  "SoapUI",
  "Integration Tests",
  "Rspec",
  "Basecamp",
  "ADO.NET",
  "Extract Transform Load (ETL)",
  "Microsoft Excel",
  "Windows Presentation Foundation",
  "PIC Microcontroller",
  "Firebug",
  "Notepad (Software)",
  "Java Virtual Machine (JVM)",
  "New Relic (SaaS)",
  "WildFly (JBoss AS)",
  "Zend Framework",
  "Maintenance",
  "Computer Security",
  "Bugzilla",
  "Data Storage Technologies",
  "Solaris (Operating System)",
  "Apache Solr",
  "Crypto Currency",
  "Meteor",
  "AWS ECS",
  // "Knowledge of Engineering",
  "Travis Ci",
  // "Hard Work and Dedication",
  "JavaScript Libraries",
  "Network Protocols",
  "Solution Architecture",
  "Firewalls (Computer Science)",
  "Microsoft Word",
  "Enterprise JavaBeans",
  "IBM DB2",
  "Sybase",
  "Toad (Software)",
  "Pulumi",
  "Assembly and Installation",
  "Website Wireframe",
  "Search Engine Optimization",
  "Microsoft Visio",
  "Transact-SQL",
  "JavaServer Pages Standard Tag Library",
  "Magento",
  "GPT",
  "Vba Programming Language",
  "Google Maps",
  "Ability to Multitask",
  "Nunit",
  "HTML Abstraction Markup Language",
  "Team Management",
  "Vim (Text Editor)",
  "Cloudformation",
  "LAMP (Software Bundle)",
  "Amazon Cloudfront",
  "Power BI",
  "MapReduce",
  "NLTK (NLP Analysis)",
  "Apache Hive",
  "Hyperledger",
  "Grails (Framework)",
  "Adobe Coldfusion",
  "Angular Material",
  "Apache ActiveMQ",
  "FFmpeg",
  "Memcached",
  "InVision",
  "Target Market Selection",
  "CMake",
  "OpenGL",
  "Quick EMUlator (QEMU)",
  "Test Scripts",
  "Business Requirements",
  "Order Picking",
  "Self Motivation",
  "Data Structures",
  "Health Level Seven International",
  "Load Balancing",
  "Relational Databases",
  "Highcharts",
  "Jinja (Template Engine)",
  "Airflow",
  "Data Processing",
  "Data Visualization",
  "Swiftui",
  "Technical Skills",
  "Apple Xcode",
  "Elixir",
  "ASP.NET MVC Framework",
  "OpenShift",
  "Architectural Design",
  "Innovation",
  "Model View ViewModel",
  "Multithreading",
  "Zeplin",
  "HAProxy",
  "Svelte",
  "User Authentication",
  "Smart Contracts",
  "Teamcity",
  "Datadog",
  "Java API for RESTful Web Services (JAX-RS)",
  "Unix Shell",
  "Dashboards",
  "Yii PHP Framework",
  "Confident and Emotionally Stable",
  //"Positive Attitude",
  "Celery",
  "Google Web Toolkits",
  "WebRTC",
  "Performance Tuning",
  "Selenium Webdriver",
  "Mulesoft",
  "Appium",
  "Gherkin",
  "Database Design",
  "Requirements Analysis",
  "Active Directory",
  "Generative AI",
  "Druid",
  // "Knowledge of Statistics",
  "Robotics Design and Production",
  "Functional Programming",
  "Auditing Skills",
  "Apache Cordova",
  "Crystal Reports (Reporting Software)",
  "File Transfer Protocol (FTP)",
  "SQL Server Integration Services",
  "SQL Server Reporting Services",
  "Macros",
  "Supply Chain Management",
  "Design Elements and Principles",
  "E2e Testing",
  "Sinatra (Software)",
  "Marketing Planning",
  "SolidWorks (CAD)",
  "Employee Onboarding",
  //"Clinical Works",
  "Operability",
  "Backbone.Js",
  "Apache Flink",
  "Apache IBATIS",
  // "Dynamo",
  "MyBatis",
  "TCP/IP",
  "Domain Name System (DNS)",
  "Nagios",
  "Zabbix",
  "Angular Ui",
  "Incident Response",
  "Hardware Infrastructure",
  "Technical Support",
  "Preventive Maintenance",
  "IBM Rational Unified Process",
  "Microsoft WebMatrix",
  "HP Loadrunner",
  "IBM AIX",
  "CorelDRAW (Corel Software)",
  "CouchDB",
  "Mercurial",
  "Redmine",
  "Distributed Systems",
  "Sendgrid",
  "WebStorm",
  "Virtualization Technology",
  "Electrical Rule Check",
  "Scalability",
  "Delivery of Projects",
  "Budgeting Skills",
  "Iframes",
  "Certified Information Systems Security Professional",
  "Embedded Computers",
  "IBM Watson",
  "Jetty",
  "Microsoft Visual SourceSafe",
  "Contentful",
  "Sanity.io",
  "Webhooks",
  "Digital Marketing",
  "Windows Forms",
  "Apache Camel",
  "AWS Fargate",
  "Extensible Stylesheet Language (XSL)",
  "Glassfish Application Servers",
  "Universal Description Discovery and Integration",
  "Pascal (Programming Language)",
  "Real Estate",
  "Web Platforms",
  "Agriculture",
  "Well-being and Personal Care",
  "Newrelic",
  "Product Management",
  ".NET Framework 4",
  "SQL Server Management Studio (SSMS)",
  "Windows Servers",
  "Customer Relationship Management",
  "Capistrano",
  "CoffeeScript",
  "Continuous Delivery",
  "Microarchitecture",
  "Workflows",
  "A/B Testing",
  "Adobe Analytics",
  "Building Codes",
  "Reliability",
  "Spock",
  "Istio",
  "Quartz (Graphics Layer)",
  "Symphony",
  "Administrative Operations",
  "Hadoop Distributed File System",
  "Jupyter",
  "Lex (Software)",
  "SciPy",
  "Xgboost",
  "Liquibase",
  "Payment Gateway",
  "Banking Services",
  "Cisco",
  "Influxdb",
  "Query Performance",
  "Project Planning",
  "Call Centers",
  "Apache Lucene",
  "Aws Command Line Interface (CLI)",
  "SQL Server Management Studio",
  "Stripe",
  "Web Application Security",
  "Burn Down Chart",
  "Cisco Unified Communications Manager",
  "OTRS",
  "Productivity Software",
  "Gantt Charts",
  "Forecasting Skills",
  "Compilers",
  "Kernel Debuggers",
  "Nvidia CUDA",
  "OpenMP",
  "Spacy",
  "Knowledge of Plumbing",
  "User-Centered Design",
  "Customer Communications Management",
  "Receptivity",
  "Telephone Skills",
  "Software Library",
  "Network Security",
  "Cadence Virtuoso",
  "Teaching",
  "Webflow",
  "Uikit",
  "Perforce",
  "Neo4j",
  "Creating Prototypes",
  "CentOS",
  "PHP Development",
  "PHP Frameworks",
  "Presentations",
  "Brand Management",
  "Audience Measurement",
  "Customer Experience",
  "Pair Programming",
  "Software Architecture",
  "Database Tools and Utilities",
  "Dialectical Behavior Therapy",
  "Visual Effects",
  "Ios Frameworks",
  "Lean Processes",
  "Performance Management",
  "Passionate",
  "Markup Languages",
  "Queueing Systems",
  "BigTable",
  "Google App Engines",
  "Zendesk",
  "Anaconda",
  "Elastic Beanstalk",
  "Regular Expressions",
  "Knowledge of Mathematics",
  "Economy",
  "Cloudflare",
  "Rancher",
  "Sourcetree",
  "Boomi",
  "Technology Integration",
  "Elk Stack",
  "3d Models",
  "Quantum GIS (QGIS)",
  "Blenders",
  "M Programming Language",
  "Katalon Studio",
  "Access Controls",
  "Medical Records",
  "Health Care",
  "Project Scoping",
  "Business Logic",
  "Tokenization",
  "Reliability Engineering",
  "Strategic Alliances",
  "Continuous Training",
  "Emotional Intelligence",
  "Mustache",
  "Perl (Programming Language)",
  "Protocol Buffers",
  "Qt Modeling Language (QML)",
  "DocuSign",
  "Cloud Computing Security",
  "Microsoft Teams",
  "Bitcoin",
  "Application Data",
  "JavaServer Faces",
  "Webdriver",
  "Dask",
  "Yahoo! User Interface Library (YUI)",
  "Dynamic HTML",
  "Scripting",
  "XMLSpy",
  "Web Analytics",
  "Adobe Flash",
  "Visualization",
  "Facebook Ads Api",
  "Google AdSense",
  "Rich Site Summary (RSS)",
  "Ember.Js",
  "Financial Management",
  "SAP Applications",
  "Apache JMeter",
  "Apache Zookeeper",
  "Logstash",
  "Mule",
  "Eloqua",
  // "Browser Compatibility",
  // "Bug Tracking Systems",
  "Pentaho Data Integration",
  // "Robot Framework",
  // "Cooking Skills",
  // "Martial Arts",
  // "Judo",
  "ZFS File System",
  "Slurm",
  "Kernel-Based Virtual Machine",
  "U-Boot",
  "Unreal Engine",
  "WebGL",
  "DirectX (Software)",
  "NFT",
  // "Code Restructuring",
  // "Program Optimization",
  // "Software Systems",
  // "Technical Documentation",
  // "User Guide",
  // "Computer-Aided Design",
  // "Management Software",
  // "Coordination Skills",
  // "Software Applications",
  // "Strategic Management",
  // "JAWS Scripting Language",
  // "Google Play",
  // "Material Design",
  // "Infrastructure Design",
  // "Code Coverage",
  "Protractor",
  //"Singleton Pattern",
  "Apex Code",
  "Bower",
  "Bundler",
  "CakePHP",
  // "IBM Notes",
  // "Salesforce.Com",
  "Powerapps",
  "Microsoft SharePoint",
  "Multitier Architecture",
  // "Team Foundation Server",
  // "Moodle",
  // "Gerrit",
  // "Vert.x",
  // "Iec61131-3",
  // "Query Optimization",
  // "BigQuery",
  "Large Language Models",
  // "Recommender Systems",
  // "Risk Management",
  // "Angular 2+",
  // "Dynatrace",
  // "Chatbots",
  // "Parsing",
  // "Vmware",
  // "OpenStack",
  // "Time Series",
  // "Service-Oriented Architecture",
  "Message Queuing Telemetry Transport (MQTT)",
  "SailPoint",
  "SAP HANA",
  // "Business Analysis",
  // "Manufacturing",
  // "Negotiation of Contracts",
  // "Amazon Redshift",
  // "Data Security",
  // "Spring Jdbc",
  // "Blazor",
  "OpenID",
  // "Gitlab-ci",
  // "Test Engineering",
  // "Computer Vision",
  // "Command-Line Interface",
  // "Asynchronous Programming",
  // "Printed Circuit Board",
  // "Electrical Switches",
  "PuTTY",
  // "Document Management Systems",
  "Puppet",
];
export const skills_test = [
  "Perl (Programming Language)",
  "Protocol Buffers",
  "Qt Modeling Language (QML)",
  "DocuSign",
  "Cloud Computing Security",
  "Microsoft Teams",
  "Bitcoin",
  "Application Data",
  "JavaServer Faces",
  "Webdriver",
  "Dask",
  "Yahoo! User Interface Library (YUI)",
  "Dynamic HTML",
  "Scripting",
  "XMLSpy",
  "Web Analytics",
  "Adobe Flash",
  "Visualization",
  "Facebook Ads Api",
  "Google AdSense",
  "Rich Site Summary (RSS)",
  "Ember.Js",
  "Financial Management",
  "SAP Applications",
  "Apache JMeter",
  "Apache Zookeeper",
  "Logstash",
  "Mule",
  "Eloqua",
  // "Browser Compatibility",
  // "Bug Tracking Systems",
  "Pentaho Data Integration",
  // "Robot Framework",
  // "Cooking Skills",
  // "Martial Arts",
  // "Judo",
  "ZFS File System",
  "Slurm",
  "Kernel-Based Virtual Machine",
  "U-Boot",
  "Unreal Engine",
  "WebGL",
  "DirectX (Software)",
  "NFT",
  // "Code Restructuring",
  // "Program Optimization",
  // "Software Systems",
  // "Technical Documentation",
  // "User Guide",
  // "Computer-Aided Design",
  // "Management Software",
  // "Coordination Skills",
  // "Software Applications",
  // "Strategic Management",
  // "JAWS Scripting Language",
  "Google Play",
  "Material Design",
  // "Infrastructure Design",
  // "Code Coverage",
  "Protractor",
  //"Singleton Pattern",
  "Apex Code",
  "Bower",
  "Bundler",
  "CakePHP",
  // "IBM Notes",
  // "Salesforce.Com",
  "Powerapps",
  "Microsoft SharePoint",
  "Multitier Architecture",
  // "Team Foundation Server",
  // "Moodle",
  "Gerrit",
  // "Vert.x",
  // "Iec61131-3",
  // "Query Optimization",
  "BigQuery",
  "Large Language Models",
  // "Recommender Systems",
  // "Risk Management",
  // "Angular 2+",
  "Dynatrace",
  "Chatbots",
  // "Parsing",
  "Vmware",
  "OpenStack",
  // "Time Series",
  // "Service-Oriented Architecture",
  "Message Queuing Telemetry Transport (MQTT)",
  "SailPoint",
  "SAP HANA",
  // "Business Analysis",
  // "Manufacturing",
  // "Negotiation of Contracts",
  "Amazon Redshift",
  // "Data Security",
  "Spring Jdbc",
  // "Blazor",
  "OpenID",
  // "Gitlab-ci",
  // "Test Engineering",
  // "Computer Vision",
  // "Command-Line Interface",
  // "Asynchronous Programming",
  // "Printed Circuit Board",
  // "Electrical Switches",
  "PuTTY",
  // "Document Management Systems",
  "Puppet",
];
